-- AlterTable
ALTER TABLE "sale_order" ADD COLUMN     "amount_tax" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "subtotal" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "total" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
